base_model: meta-llama/Llama-2-13b-chat-hf
base_model_config: meta-llama/Llama-2-13b-chat-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path:
    type: sharegpt
dataset_prepared_path: last_run_prepared
hub_model_id:
val_set_size: 0.01
output_dir: ./test_model

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
# eval_sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model: "checkpoint"


gradient_accumulation_steps: 4
micro_batch_size: 2
eval_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

resize_token_embeddings_to_32x: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 5
eval_table_size: 10
save_steps:
debug:
deepspeed:
weight_decay: 0.0
# fsdp:
#   - full_shard
#   - auto_wrap
# fsdp_config:
#   fsdp_offload_params: true
#   fsdp_state_dict_type: FULL_STATE_DICT
#   fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"